<template>
  <div>
    <!-- Back Arrow -->
    <div class="mb-10" @click="$router.back()">
      <v-icon color="green darken-2" left> mdi-arrow-left </v-icon>
      <span class="text-color back"> Back </span>
    </div>
    <h2>User</h2>
    <p class="font-weight-light">Users>>Create New Users</p>

    <div>
      <p class="text-center font-weight-bold display-1">Create New User</p>
      <v-container>
        <v-layout class="">
          <v-flex xs12 sm12 md9 lg6 class="mt-6">
            <!-- <v-container> -->
            <v-layout>
              <v-flex xs12 sm8 md9>
                <v-form class="pa-0">
                  <v-row cols="12" md="6" lg="2">
                    <template>
                      <v-col cols="12" md="12" sm="12" xs="12">
                        <div>
                          <p class="mb-2 text-color">
                            Select Your User Details
                          </p>
                          <div class="mb-2">
                            <label>Username</label>
                          </div>
                          <div>
                            <v-text-field
                              v-model="name"
                              outlined
                            ></v-text-field>
                          </div>
                        </div>
                      </v-col>
                    </template>
                  </v-row>
                </v-form>
              </v-flex>
            </v-layout>
            <!-- </v-container> -->
          </v-flex>
        </v-layout>
        <v-container>
          <div class="hr-sect"></div>
        </v-container>
        <div class="mb-8">
          <p class="mb-2 text-color">Select Your User Details</p>
          <p>
            Select how this user will access One-Runner, Acess Keys and
            autogenerated password are proided in the last step
          </p>
        </div>
        <div class="mb-6">
          <v-checkbox v-model="selected" color="success">
            <template v-slot:label>
              <div class="font-weight-bold"><b>Programmatic Access</b></div>
            </template>
          </v-checkbox>
          <p class="ml-7">
            Enables an <b>Access Key Id</b> and <b>Secret Access Key</b> for all
            development tool
          </p>
        </div>
        <div>
          <v-checkbox v-model="selected" color="success">
            <template v-slot:label>
              <div class="font-weight-bold">
                <b>One-Runner Console Access</b>
              </div>
            </template>
          </v-checkbox>

          <p class="ml-7">
            Enables a <b>Password</b> that allow users to sign in to
            One-Runner-Console
          </p>
        </div>
        <div v-if="selected">
          <v-container>
            <div class="ml-10">
              <p class="text-color">Create Password</p>
              <v-radio-group v-model="radios" mandatory>
                <v-radio color="green">
                  <template v-slot:label>
                    <div>
                      <strong> Autogenerated Password</strong>
                    </div>
                  </template>
                </v-radio>
                <v-radio color="green">
                  <template v-slot:label>
                    <div>
                      <strong>Custom Password</strong>
                    </div>
                  </template>
                </v-radio>
              </v-radio-group>
              <div class="ml-7">
                <div class="mb-2">
                  <label>Create Password</label>
                </div>
                <div>
                  <v-row>
                    <v-col cols="12" md="4">
                      <div>
                        <v-text-field v-model="name" outlined></v-text-field>
                      </div>
                    </v-col>
                  </v-row>
                </div>
              </div>
              <div>
                <p class="text-color">Register Password Reset</p>
                <v-checkbox v-model="select" color="success">
                  <template v-slot:label>
                    <div>
                      <p class="mt-5">
                        User must create a new passwordat next Sign-in
                      </p>
                    </div>
                  </template>
                </v-checkbox>
              </div>
            </div>
          </v-container>
        </div>
      </v-container>
      <div>
        <div class="float-left mt-4 mb-4 text-center">
          <v-btn outlined height="50"> Cancel </v-btn>
        </div>

        <div class="float-right mt-4 text-center">
          <v-btn color="success" block height="50" @click="createUsers">
            Create
          </v-btn>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      selected: false,
    }
  },
}
</script>

<style scoped>
.text-color {
  color: #29c038;
}
.horizontal-line {
  border: 1px solid #e0e0e0;
}
.hr-sect {
  display: flex;
  flex-basis: 100%;
  /* align-items: center; */
  color: rgba(0, 0, 0, 0.35);
  margin: 8px 0px;
}
.hr-sect::before,
.hr-sect::after {
  content: '';
  flex-grow: 1;
  border: 1px solid #e0e0e0;
  height: 1px;
  font-size: 0px;
  line-height: 0px;
  margin: 0px 8px;
}
</style>
